import { WasteListing, BuyerDemand, Match, Message, Profile } from './types';

export const MOCK_PROFILES: Profile[] = [
  {
    id: 'usr_f1',
    full_name: 'Wanjiku Kamau',
    phone_number: '+254 712 345 678',
    role: 'farmer',
    organization_name: 'Githunguri Smallholders Coop',
    county: 'Kiambu',
    sub_county: 'Githunguri',
    latitude: -1.0568,
    longitude: 36.7788,
    avatar_url: null,
    created_at: '2026-08-10T08:00:00Z',
    updated_at: '2026-08-10T08:00:00Z',
  },
  {
    id: 'usr_f2',
    full_name: 'Juma Omondi',
    phone_number: '+254 723 456 789',
    role: 'farmer',
    organization_name: 'Muhoroni Cane Producers',
    county: 'Kisumu',
    sub_county: 'Muhoroni',
    latitude: -0.1542,
    longitude: 35.1983,
    avatar_url: null,
    created_at: '2026-08-12T09:30:00Z',
    updated_at: '2026-08-12T09:30:00Z',
  },
  {
    id: 'usr_f3',
    full_name: 'Kiprono Cheruiyot',
    phone_number: '+254 734 567 890',
    role: 'farmer',
    organization_name: 'Rongai Grain Growers',
    county: 'Nakuru',
    sub_county: 'Rongai',
    latitude: -0.1742,
    longitude: 35.8644,
    avatar_url: null,
    created_at: '2026-08-15T11:00:00Z',
    updated_at: '2026-08-15T11:00:00Z',
  },
  {
    id: 'usr_b1',
    full_name: 'Dr. Kevin Mutua',
    phone_number: '+254 701 223 344',
    role: 'buyer',
    organization_name: 'GreenFlame Briquettes Ltd',
    county: 'Nakuru',
    sub_county: 'Nakuru Town West',
    latitude: -0.2833,
    longitude: 36.0667,
    avatar_url: null,
    created_at: '2026-08-01T10:00:00Z',
    updated_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'usr_b2',
    full_name: 'Amina Hassan',
    phone_number: '+254 722 998 877',
    role: 'buyer',
    organization_name: 'Lakeside BioPower & Feed',
    county: 'Kisumu',
    sub_county: 'Kisumu Central',
    latitude: -0.0917,
    longitude: 34.7680,
    avatar_url: null,
    created_at: '2026-08-05T14:20:00Z',
    updated_at: '2026-08-05T14:20:00Z',
  },
];

export const MOCK_LISTINGS: WasteListing[] = [
  {
    id: 'lst_1',
    farmer_id: 'usr_f3',
    waste_type: 'maize_stalks',
    quantity_kg: 12500,
    description: 'Post-harvest clean dry maize stover and stalks, baled and stacked under shed. Ready for transport.',
    condition: 'dried',
    available_from: '2026-08-25',
    available_until: '2026-09-30',
    latitude: -0.1742,
    longitude: 35.8644,
    location_name: 'Rongai, Nakuru County',
    status: 'active',
    images: ['/images/maize-stalks.jpg'],
    created_at: '2026-08-26T08:30:00Z',
    updated_at: '2026-08-26T08:30:00Z',
    farmer: MOCK_PROFILES[2],
  },
  {
    id: 'lst_2',
    farmer_id: 'usr_f2',
    waste_type: 'sugarcane_bagasse',
    quantity_kg: 28000,
    description: 'High-fiber freshly crushed sugarcane bagasse from local jaggery & outgrower plots. Ideal for biogas digestion.',
    condition: 'fresh',
    available_from: '2026-08-28',
    available_until: '2026-10-15',
    latitude: -0.1542,
    longitude: 35.1983,
    location_name: 'Muhoroni, Kisumu County',
    status: 'active',
    images: ['/images/bagasse.jpg'],
    created_at: '2026-08-28T10:15:00Z',
    updated_at: '2026-08-28T10:15:00Z',
    farmer: MOCK_PROFILES[1],
  },
  {
    id: 'lst_3',
    farmer_id: 'usr_f1',
    waste_type: 'coffee_husks',
    quantity_kg: 8500,
    description: 'Dry parchment and cherry husks from secondary milling factory. Uniform particle size, high calorific value.',
    condition: 'dried',
    available_from: '2026-08-20',
    available_until: '2026-10-01',
    latitude: -1.0568,
    longitude: 36.7788,
    location_name: 'Githunguri, Kiambu County',
    status: 'active',
    images: ['/images/coffee-husks.jpg'],
    created_at: '2026-08-22T07:45:00Z',
    updated_at: '2026-08-22T07:45:00Z',
    farmer: MOCK_PROFILES[0],
  },
  {
    id: 'lst_4',
    farmer_id: 'usr_f3',
    waste_type: 'maize_cobs',
    quantity_kg: 6200,
    description: 'Clean shelled maize cobs with low moisture content (<12%). High bulk density for briquetting carbonization.',
    condition: 'dried',
    available_from: '2026-08-29',
    available_until: '2026-09-25',
    latitude: -0.2100,
    longitude: 35.9100,
    location_name: 'Njoro, Nakuru County',
    status: 'active',
    images: ['/images/maize-cobs.jpg'],
    created_at: '2026-08-29T14:10:00Z',
    updated_at: '2026-08-29T14:10:00Z',
    farmer: MOCK_PROFILES[2],
  },
];

export const MOCK_DEMANDS: BuyerDemand[] = [
  {
    id: 'dmd_1',
    buyer_id: 'usr_b1',
    waste_type: 'maize_stalks',
    quantity_kg_min: 5000,
    quantity_kg_max: 20000,
    preferred_condition: 'dried',
    use_case: 'briquettes',
    description: 'Urgently sourcing dry biomass (maize stalks/cobs) for smokeless eco-briquette factory in Nakuru.',
    needed_by: '2026-09-15',
    latitude: -0.2833,
    longitude: 36.0667,
    location_name: 'Nakuru Town Industrial Area',
    max_distance_km: 60,
    status: 'active',
    created_at: '2026-08-20T12:00:00Z',
    updated_at: '2026-08-20T12:00:00Z',
    buyer: MOCK_PROFILES[3],
  },
  {
    id: 'dmd_2',
    buyer_id: 'usr_b2',
    waste_type: 'sugarcane_bagasse',
    quantity_kg_min: 15000,
    quantity_kg_max: 50000,
    preferred_condition: 'fresh',
    use_case: 'biogas',
    description: 'Continuous feedstock contract for commercial anaerobic digester and co-generation facility.',
    needed_by: '2026-10-01',
    latitude: -0.0917,
    longitude: 34.7680,
    location_name: 'Kisumu Eco-Industrial Park',
    max_distance_km: 75,
    status: 'active',
    created_at: '2026-08-22T15:30:00Z',
    updated_at: '2026-08-22T15:30:00Z',
    buyer: MOCK_PROFILES[4],
  },
  {
    id: 'dmd_3',
    buyer_id: 'usr_b1',
    waste_type: 'coffee_husks',
    quantity_kg_min: 4000,
    quantity_kg_max: 15000,
    preferred_condition: 'dried',
    use_case: 'briquettes',
    description: 'High-calorific coffee husks needed to blend with sawdust for premium industrial boiler fuel logs.',
    needed_by: '2026-09-30',
    latitude: -0.2833,
    longitude: 36.0667,
    location_name: 'Nakuru Plant',
    max_distance_km: 120,
    status: 'active',
    created_at: '2026-08-25T09:00:00Z',
    updated_at: '2026-08-25T09:00:00Z',
    buyer: MOCK_PROFILES[3],
  },
];

export const MOCK_MATCHES: Match[] = [
  {
    id: 'mtc_1',
    listing_id: 'lst_1',
    demand_id: 'dmd_1',
    match_score: 96,
    match_reasoning: 'Exceptional 96% match: Supply of 12.5T dry maize stalks in Rongai is only 21km from the Nakuru briquette factory. Dried condition perfectly satisfies buyer specification with immediate transport availability.',
    distance_km: 21.4,
    status: 'accepted',
    created_at: '2026-08-27T09:12:00Z',
    listing: MOCK_LISTINGS[0],
    demand: MOCK_DEMANDS[0],
  },
  {
    id: 'mtc_2',
    listing_id: 'lst_2',
    demand_id: 'dmd_2',
    match_score: 92,
    match_reasoning: 'Strong 92% match: 28 tons fresh sugarcane bagasse in Muhoroni matches Kisumu biogas plant feedstock demands. 48km haulage route along direct highway with high moisture content ideal for anaerobic digestion.',
    distance_km: 48.6,
    status: 'pending',
    created_at: '2026-08-28T11:00:00Z',
    listing: MOCK_LISTINGS[1],
    demand: MOCK_DEMANDS[1],
  },
  {
    id: 'mtc_3',
    listing_id: 'lst_4',
    demand_id: 'dmd_1',
    match_score: 89,
    match_reasoning: 'High 89% match: 6.2T clean dry cobs in Njoro is just 14km from the briquette manufacturing plant. Excellent calorific density for carbonization.',
    distance_km: 14.1,
    status: 'pending',
    created_at: '2026-08-29T15:00:00Z',
    listing: MOCK_LISTINGS[3],
    demand: MOCK_DEMANDS[0],
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg_1',
    match_id: 'mtc_1',
    sender_id: 'usr_b1',
    content: 'Jambo Kiprono! We reviewed your 12.5T maize stalk listing in Rongai. The moisture condition looks great for our briquetting line.',
    created_at: '2026-08-27T10:00:00Z',
    sender: MOCK_PROFILES[3],
  },
  {
    id: 'msg_2',
    match_id: 'mtc_1',
    sender_id: 'usr_f3',
    content: 'Habari Dr. Kevin! Yes, everything is baled and covered under our storage shed. Can your 10-ton flatbed truck access our farm road?',
    created_at: '2026-08-27T10:15:00Z',
    sender: MOCK_PROFILES[2],
  },
  {
    id: 'msg_3',
    match_id: 'mtc_1',
    sender_id: 'usr_b1',
    content: 'Yes, our logistics partner can dispatch this Friday morning. We offer KES 3.80 per kg delivered or KES 2.60 farm-gate pickup.',
    created_at: '2026-08-27T10:30:00Z',
    sender: MOCK_PROFILES[3],
  },
  {
    id: 'msg_4',
    match_id: 'mtc_1',
    sender_id: 'usr_f3',
    content: 'Farm-gate pickup at KES 2.60 works well for us. Let us finalize loading times for Friday 8:00 AM.',
    created_at: '2026-08-27T11:00:00Z',
    sender: MOCK_PROFILES[2],
  },
];
